[project]
name = "bessie"
version = "0.1.0"
description = "BESS modelling in the NEM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.9.0",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
]
